const homePageStyles = {
  root: {
    flexGrow: 1,
    minHeight: '100vh',
    color: '#FFFFFF',
    maxWidth: '2400px !important',
  },
  
  // Hero Section
  hero: {
    position: 'relative',
    overflow: 'hidden',
    pt: { xs: 12, md: 12 },
    pb: { xs: 8, md: 8 },
    background: '#000000',
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'radial-gradient(circle at 20% 30%, rgba(0, 0, 0, 0.8) 0%, #000000 70%)',
      zIndex: 0,
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      top: '20%',
      right: '10%',
      width: '500px',
      height: '500px',
      background: 'radial-gradient(circle, rgba(0, 231, 255, 0.1) 0%, transparent 70%)',
      zIndex: 0,
    },
  },
  heroContainer: {
    width: '100%',
    maxWidth: '1800px !important',
    marginLeft: 'auto',
    marginRight: 'auto',
    position: 'relative',
    zIndex: 1,
    paddingLeft: '0px !important',
    paddingRight: '0px !important',
  },
  heroContent: {
    width: '100%',
    maxWidth: '1800px',
    mx: 'auto',
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: { xs: 4, md: 8 },
  },
  heroText: {
    flex: 1,
    maxWidth: '800px',
    textAlign: 'left',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    minWidth: 0,
  },
  heroTitle: {
    fontSize: { xs: '2.75rem', md: '3.75rem', lg: '4.5rem' },
    fontWeight: 800,
    lineHeight: 1.1,
    mb: 4,
    color: '#F8FAFC',
    textAlign: 'left',
    width: '100%',
    maxWidth: '1000px',
    whiteSpace: 'normal',
    position: 'relative',
    zIndex: 1,
    '& span': {
      background: 'linear-gradient(90deg, #38BDF8 0%, #0EA5E9 100%)',
      WebkitBackgroundClip: 'text',
      WebkitTextFillColor: 'transparent',
      position: 'relative',
      '&::after': {
        content: '""',
        position: 'absolute',
        bottom: '-4px',
        left: 0,
        width: '100%',
        height: '3px',
        background: 'linear-gradient(90deg, #38BDF8 0%, #0EA5E9 100%)',
        borderRadius: '2px',
      },
    },
  },
  heroTagline: {
    fontSize: { xs: '1.5rem', md: '2rem' },
    fontWeight: 700,
    mb: 3,
    background: 'linear-gradient(90deg, #6A83C2 0%, #8268E0 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    textAlign: 'center',
  },
  heroSubtitle: {
    fontSize: { xs: '1.15rem', md: '1.35rem' },
    color: '#CBD5E1',
    mb: 6,
    lineHeight: 1.8,
    maxWidth: '650px',
    textAlign: 'left',
    fontWeight: 400,
    position: 'relative',
    zIndex: 1,
    opacity: 0.9,
  },
  
  // Dashboard Card
  dashboardCard: {
    background: 'rgba(26, 16, 61, 0.6)',
    borderRadius: '12px',
    border: '1px solid rgba(255, 215, 0, 0.2)',
    backdropFilter: 'blur(10px)',
    overflow: 'hidden',
    width: '100%',
    maxWidth: '600px',
    boxShadow: '0 15px 35px rgba(0, 0, 0, 0.3)',
    margin: '0 auto',
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative',
    zIndex: 1,
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'linear-gradient(135deg, rgba(255, 215, 0, 0.03) 0%, transparent 100%)',
      zIndex: -1,
    },
    '&:hover': {
      transform: 'translateY(-8px)',
      boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
      borderColor: 'rgba(255, 215, 0, 0.4)',
    },
  },
  featureCard: {
    height: '100%',
    background: 'rgba(10, 15, 30, 0.5)',
    border: '1px solid rgba(0, 231, 255, 0.1)',
    borderRadius: '16px',
    padding: '40px 32px',
    transition: 'all 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
    position: 'relative',
    overflow: 'hidden',
    backdropFilter: 'blur(10px)',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'linear-gradient(135deg, rgba(0, 180, 255, 0.05) 0%, transparent 100%)',
      zIndex: -1,
      transition: 'all 0.4s ease',
    },
    '&:hover': {
      transform: 'translateY(-10px) scale(1.02)',
      boxShadow: [
        '0 4px 20px rgba(0, 200, 255, 0.15)',
        '0 0 40px rgba(0, 180, 255, 0.1)'
      ].join(','),
      borderColor: 'rgba(0, 231, 255, 0.3)',
      background: 'rgba(15, 20, 40, 0.7)',
      '&::before': {
        background: 'linear-gradient(135deg, rgba(0, 180, 255, 0.1) 0%, transparent 100%)',
      },
      '& $featureIconContainer': {
        transform: 'scale(1.05) rotate(5deg)',
        boxShadow: '0 0 30px rgba(0, 200, 255, 0.3)',
      },
      '& $featureTitle': {
        '&::after': {
          width: '80px',
          background: '#00E7FF',
        },
      },
    },
  },
  dashboardHeader: {
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    px: 3,
  },
  dashboardTabs: {
    display: 'flex',
    gap: '8px',
    pt: 2,
  },
  dashboardTab: {
    padding: '8px 16px',
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: '0.875rem',
    cursor: 'pointer',
    '&:hover': {
      color: 'white',
    },
  },
  dashboardTabActive: {
    extend: 'dashboardTab',
    color: 'white',
    borderBottom: '2px solid #6A83C2',
    fontWeight: 600,
  },
  dashboardContent: {
    p: 3,
  },
  dashboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '16px',
    mb: 3,
  },
  metricCard: {
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '12px',
    padding: '16px',
    transition: 'all 0.3s ease',
    '&:hover': {
      background: 'rgba(106, 131, 194, 0.1)',
      transform: 'translateY(-2px)',
    },
  },
  metricTitle: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: '0.875rem',
    mb: 1,
  },
  metricValue: {
    color: 'white',
    fontWeight: 700,
    mb: 0.5,
  },
  metricChange: {
    color: '#FF6B6B',
    fontSize: '0.75rem',
  },
  chartCard: {
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '12px',
    padding: '16px',
    mt: 2,
  },
  chartPlaceholder: {
    height: '200px',
    display: 'flex',
    flexDirection: 'column',
  },
  chartLines: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    height: '100%',
    mt: 'auto',
    gap: '8px',
  },
  chartBar: {
    background: 'linear-gradient(to top, #6A83C2, #8268E0)',
    borderRadius: '4px 4px 0 0',
    width: '100%',
    minHeight: '4px',
    transition: 'all 0.3s ease',
    '&:hover': {
      opacity: 0.8,
    },
  },
  activityCard: {
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '12px',
    padding: '16px',
    mt: 2,
  },
  activityItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 0',
    borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
    '&:last-child': {
      borderBottom: 'none',
      paddingBottom: 0,
    },
  },
  activityDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  
  // CTA Buttons
  ctaButtons: {
    display: 'flex',
    justifyContent: 'center',
    mt: 4,
    '& > *': {
      flex: '1 1 auto',
      '@media (max-width: 600px)': {
        flex: '1 1 100%',
      },
    },
  },
  primaryButton: {
    background: 'linear-gradient(90deg, #6A83C2 0%, #8268E0 100%)',
    color: 'white',
    borderRadius: '8px',
    px: 4,
    py: 1.5,
    textTransform: 'none',
    fontSize: '1rem',
    fontWeight: 600,
    '&:hover': {
      background: 'linear-gradient(90deg, #5A73B0 0%, #7258C7 100%)',
      boxShadow: '0 4px 12px rgba(106, 131, 194, 0.3)',
    },
  },

  // Features Section
  features: {
    py: { xs: 12, md: 16 },
    position: 'relative',
    overflow: 'hidden',
    background: 'linear-gradient(135deg, #000000 0%, #0A0F1E 100%)',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'radial-gradient(circle at 20% 30%, rgba(0, 100, 200, 0.1) 0%, transparent 40%)',
      zIndex: 0,
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: '10%',
      right: '10%',
      width: '500px',
      height: '500px',
      background: 'radial-gradient(circle, rgba(0, 200, 255, 0.08) 0%, transparent 70%)',
      zIndex: 0,
    },
  },
  sectionTitle: {
    paddingBottom: '16px',
    fontSize: { xs: '2.5rem', md: '3.5rem' },
    fontWeight: 800,
    color: '#FFFFFF',
    textAlign: 'center',
    display: 'inline-block',
    '&::after': {
      content: '""',
      bottom: '-12px',
      left: '50%',
      transform: 'translateX(-50%)',
      width: '100px',
      height: '3px',
      background: '#00E7FF',
      borderRadius: '2px',
    },
  },
  heroSubtitle: {
    fontSize: { xs: '1.15rem', md: '1.35rem' },
    color: '#E5E7EB',
    mb: 6,
    lineHeight: 1.8,
    maxWidth: '650px',
    textAlign: 'left',
    fontWeight: 400,
    position: 'relative',
    zIndex: 1,
    opacity: 0.9,
  },
  featureIconContainer: {
    width: '80px',
    height: '80px',
    borderRadius: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '32px',
    background: 'linear-gradient(135deg, rgba(0, 180, 255, 0.1) 0%, rgba(0, 231, 255, 0.1) 100%)',
    border: '1px solid rgba(0, 231, 255, 0.15)',
    color: '#00E7FF',
    fontSize: '36px',
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 4px 15px rgba(0, 180, 255, 0.1)',
    '&:hover': {
      background: 'linear-gradient(135deg, rgba(0, 200, 255, 0.2) 0%, rgba(0, 231, 255, 0.2) 100%)',
      borderColor: 'rgba(0, 231, 255, 0.4)',
      boxShadow: '0 8px 25px rgba(0, 200, 255, 0.2)',
    },
  },
  featureTitle: {
    fontSize: '1.5rem',
    fontWeight: 700,
    mb: 3,
    color: '#FFFFFF',
    position: 'relative',
    display: 'inline-block',
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: '-8px',
      left: 0,
      width: '40px',
      height: '2px',
      background: '#00E7FF',
      transition: 'width 0.3s ease',
    },
    '&:hover::after': {
      width: '60px',
    },
  },
  featureDescription: {
    fontSize: '1.1rem',
    color: '#E5E7EB',
    lineHeight: 1.8,
    opacity: 0.85,
    transition: 'all 0.3s ease',
    '&:hover': {
      opacity: 1,
      color: '#FFFFFF',
    },
  },
  
  // Pricing Section
  pricingSection: {
    paddingLeft: '24px',
    py: { xs: 12, md: 16 },
    backgroundColor: '#000000',
    position: 'relative',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'radial-gradient(circle at 50% 0%, rgba(0, 180, 255, 0.05) 0%, transparent 70%)',
      zIndex: 0,
    },
  },
  sectionSubtitle: {
    display: 'inline-block',
    backgroundColor: 'rgba(0, 200, 255, 0.1)',
    color: '#00E7FF',
    fontSize: '0.75rem',
    fontWeight: 600,
    padding: '6px 16px',
    borderRadius: '20px',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    marginBottom: '16px',
    border: '1px solid rgba(0, 231, 255, 0.2)',
  },
  pricingCard: {
    height: '100%',
    background: 'rgba(10, 20, 30, 0.5)',
    border: '1px solid rgba(0, 231, 255, 0.1)',
    borderRadius: '16px',
    padding: '40px 32px',
    transition: 'all 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
    position: 'relative',
    overflow: 'hidden',
    backdropFilter: 'blur(10px)',
    '& .pricing-badge': {
      position: 'absolute',
      top: '16px',
      right: '16px',
      backgroundColor: 'rgba(0, 200, 255, 0.2)',
      color: '#00E7FF',
      fontSize: '0.75rem',
      fontWeight: 600,
      padding: '4px 12px',
      borderRadius: '12px',
      textTransform: 'uppercase',
      letterSpacing: '0.05em',
      border: '1px solid rgba(0, 231, 255, 0.3)',
    },
    '&:hover': {
      transform: 'translateY(-8px)',
      borderColor: 'rgba(0, 231, 255, 0.3)',
      boxShadow: [
        '0 8px 30px rgba(0, 200, 255, 0.15)',
        '0 0 40px rgba(0, 180, 255, 0.1)'
      ].join(','),
    },
  },
  pricingHeader: {
    textAlign: 'center',
    mb: 4,
    pb: 3,
    borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
  },
  pricingTitle: {
    color: '#FFFFFF',
    fontWeight: 700,
    fontSize: '1.5rem',
    mb: 2,
  },
  pricingPrice: {
    fontWeight: 800,
    fontSize: '3rem',
    lineHeight: 1.2,
    background: 'linear-gradient(90deg, #00E7FF 0%, #00B8FF 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  pricingPeriod: {
    fontSize: '1rem',
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: 400,
    marginLeft: '4px',
    alignSelf: 'flex-end',
    paddingBottom: '0.5rem',
  },
  pricingFeatures: {
    my: 4,
    minHeight: '160px',
  },
  pricingFeature: {
    color: 'rgba(255, 255, 255, 0.9)',
    mb: 2,
    fontSize: '1rem',
    display: 'flex',
    alignItems: 'center',
    '&:before': {
      content: '""',
      display: 'inline-block',
      width: '24px',
      height: '24px',
      backgroundImage: 'url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'24\' height=\'24\' viewBox=\'0 0 24 24\' fill=\'none\' stroke=\'%2300E7FF\' stroke-width=\'2\' stroke-linecap=\'round\' stroke-linejoin=\'round\'%3E%3Cpolyline points=\'20 6 9 17 4 12\'%3E%3C/polyline%3E%3C/svg%3E")',
      backgroundRepeat: 'no-repeat',
      backgroundPosition: 'center',
      marginRight: '12px',
      flexShrink: 0,
    },
  },
  pricingButton: {
    py: 1.5,
    borderRadius: '8px',
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '1rem',
    color: '#FFFFFF',
    border: '1px solid rgba(0, 231, 255, 0.3)',
    background: 'rgba(0, 200, 255, 0.1)',
    width: '100%',
    transition: 'all 0.3s ease',
    '&:hover': {
      background: 'rgba(0, 231, 255, 0.2)',
      borderColor: 'rgba(0, 231, 255, 0.5)',
      boxShadow: '0 0 20px rgba(0, 200, 255, 0.2)',
    },
  },
  pricingButtonPrimary: {
    background: 'linear-gradient(90deg, #00E7FF 0%, #00B8FF 100%)',
    color: '#001A20',
    border: 'none',
    fontWeight: 700,
    '&:hover': {
      background: 'linear-gradient(90deg, #00D1FF 0%, #009EFF 100%)',
      boxShadow: '0 0 30px rgba(0, 200, 255, 0.4)',
    },
  },

  // CTA Section
  ctaSection: {
    py: { xs: 12, md: 16 },
    position: 'relative',
    background: 'linear-gradient(135deg, #0B081C 0%, #1A162E 100%)',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'radial-gradient(circle at 70% 30%, rgba(106, 131, 194, 0.15) 0%, rgba(16, 12, 36, 0) 70%)',
      zIndex: 0,
    },
  },
  ctaContainer: {
    position: 'relative',
    zIndex: 1,
    textAlign: 'center',
    padding: { xs: '40px 20px', md: '60px 40px' },
    borderRadius: '24px',
    background: 'rgba(255, 255, 255, 0.03)',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.2)',
  },
  ctaTitle: {
    fontWeight: 800,
    fontSize: { xs: '2rem', md: '3rem' },
    lineHeight: 1.1,
    letterSpacing: '-0.03em',
    color: 'white',
    mb: 2,
    background: 'linear-gradient(90deg, #FFFFFF 0%, #A0A0A0 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  ctaSubtitle: {
    fontSize: '1.25rem',
    lineHeight: 1.7,
    color: 'rgba(255, 255, 255, 0.8)',
    mb: 4,
    maxWidth: '600px',
    mx: 'auto',
  },
  ctaButtonContainer: {
    display: 'flex',
    justifyContent: 'center',
    gap: '20px',
    flexWrap: 'wrap',
    mt: 6,
    '& button': {
      minWidth: '180px',
      padding: '14px 28px',
      fontSize: '1.1rem',
    },
  },
};

export default homePageStyles;
